# Ignore UI Components Test Path Checking for codecov
# Reason: (JavaFX Components testing is tightly coupled, causing disproportionate amounts of missed lines in report)

ignore:
  - "src/main/java/seedu/address/ui"
