# Ignore UI Components Test Path Checking for codecov
# Reason: (JavaFX Components testing is tightly coupled, causing disproportionate amounts of missed lines in report)

ignore:
  - "src/main/java/seedu/address/MainApp"
  - "src/main/java/seedu/address/ui"
  - "src/main/java/seedu/address/model/util/SampleDataUtil.java"
  - "src/test/java/seedu/address/testutil/*"
